# i = 90
try:
    print(i)
except :
    print('An exception occurred')


